Kantor/urls.py
from django.urls import path
from Kantor.views import list_lowongan, detail_pekerjaan, daftar_lowongan, list_applicants

urlpatterns = [
    path('', list_lowongan, name='list-lowongan'),
    path('tambah-lowongan/', daftar_lowongan, name='tambah-lowongan'),
    path('<pk>', detail_pekerjaan, name='detail-lowongan'),
    path('list-of-applicants/P<int:job_id>',
         list_applicants, name='list-of-applicants'),


    #path('<kode>', detail_course, name='detail-course'),
]

RumahSakit/urls.py
from django.urls import path
from . import views

app_name = 'RumahSakit'

urlpatterns = [
    path('daftarRS/', views.daftarRS, name='daftarRS'),
    path('listRS/', views.listRS, name = 'listRS'),
    path('<int:id>/', views.detailRS, name='detailRS'),
    path('ListPendaftar/<int:id>', views.list_pendaftar, name='list-pendaftar')
]

TK_PPW_C09/urls.py
from django.contrib import admin
from django.urls import path, include
from TK1_PPW import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('TK1_PPW.urls'), name='LandingPage'),
    path('Jobseeker/', include('Jobseeker.urls'), name='Jobseeker'),
    path('Kantor/', include('Kantor.urls'), name='Kantor'),
    path('VolunteerNonPerawat/', include('VolunteerNonPerawat.urls'), name='VolunteerNonPerawat'),
    path('RumahSakit/', include('RumahSakit.urls'), name='RumahSakit'),
    path('Perawat/', include('Perawat.urls'), name='Perawat'),
]

VolunteerNonPerawat/urls.py
from django.urls import path

from . import views

app_name = 'VolunteerNonPerawat'

urlpatterns = [
    path('<int:id>', views.index, name='index'),
    path('add/<int:id>', views.add_vnp, name='add-vnp'),
    # path('delete/<int:id>/', views.delete_vnp, name='delete-vnp')
]

RumahSakit/models.py
from django.db import models
from django.core.validators import MinValueValidator 

# Create your models here.
class RS(models.Model):
    nama = models.TextField(max_length=100, unique=True)
    alamat = models.TextField(max_length=150, unique=True)
    jml_prwt = models.PositiveIntegerField()
    jml_non = models.PositiveIntegerField()


    def __str__(self):
        return self.nama

RumahSakit/forms.py
from django import forms
from .models import RS

class RSForm(forms.ModelForm):
    nama = forms.CharField(
        label="Nama Rumah Sakit",
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    alamat = forms.CharField(
        label="Alamat",
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    class Meta:
        model = RS
        fields = "__all__"

RumahSakit/views.py
from django.shortcuts import render, redirect
from .models import RS
from Perawat.models import Perawat
from VolunteerNonPerawat.models import VolunteerNonPerawat
from .forms import RSForm
from django.contrib import messages
from itertools import zip_longest

# Create your views here.

def daftarRS(request):
    if request.method == "POST":
        RS_form = RSForm(request.POST)
        if RS_form.is_valid():
            RS_form.save()
        return redirect("RumahSakit:daftarRS")
    
    context = {
        "RSform" : RSForm
    }

    return render(request, 'daftar.html', context)

def listRS(request):
    context = {}
    all_RS = RS.objects.all()

    context['all_RS'] = all_RS

    return render(request, 'list-RS.html', context)

def detailRS(request, id):
    context = {}
    RSakit = RS.objects.get(id=id)

    context['RS'] = RSakit

    return render(request, 'detail-RS.html', context)

def list_pendaftar(request, id):
    context = {}
    rumahsakit = RS.objects.get(id = id)
    context['RS'] = rumahsakit
    listPerawat = Perawat.objects.filter(rumah_sakit_id = id)
    listNonPerawat = VolunteerNonPerawat.objects.filter(rumah_sakit_id = id)
    context['listVolunteer'] = zip_longest(listPerawat, listNonPerawat)

    return render(request, 'list_pendaftar.html', context)

RumahSakit/templates/daftar.html
{% extends 'RumahSakit/base.html' %} {% load static %} {% block content %}
<title>KamiBisa - Buat Lowongan Relawanmu</title>
<div>
    <img src="{% static 'RumahSakit/rs.jpg' %}" alt="" class="bg">
    <div class="formFlex">
        <div class="cardd">
            <div style="background-color: #f6f6f6;" class="containerr">
                <div>
                    <h1 class="textJudul">Membuat Lowongan Relawan di Kamibisa</h1>
                </div>
                <div style="font-family:Roboto" class="formnya">
                    <form method="post">
                        {% csrf_token %}

                        <div class="form-group">
                            {{RSform.nama.label_tag}}
                            {{RSform.nama}}
                        </div>
                        <div class="form-group">
                            {{RSform.alamat.label_tag}}
                            {{RSform.alamat}}
                        </div>
                        <label for="exampleFormControlInput1" class="label">Jumlah Relawan Perawat yang Dibutuhkan</label>
                        <input class="form-control mr-1 sks-input" type="number" min = 0 name="jml_prwt" required>
                        <br>
                        <label for="exampleFormControlInput1" class="label">Jumlah Relawan Perawat yang Dibutuhkan</label>
                        <input class="form-control mr-1 sks-input" type="number" min = 0 name="jml_non" required>
                        <button id="btnDaftar" type="submit">Submit</button>
                    </form>
                </div>
                <br><br><br><br><br>
            </div>
        </div>
    </div>
</div>
{% endblock %}

RumahSakit/templates/detail-RS.html
{% extends 'RumahSakit/base.html' %} {% load static %} {% block content %}
<title>{{ RS.nama }}</title>
<div>
    <h1 style="text-align: center;font-family:Righteous;margin-top:60px;margin-right:2.5%;font-size:250%;">
        {{ RS.nama }}</h1>
</div>

<h3 style="text-align: center;font-family:Righteous;margin-top: 3em;margin-right:2%;font-size:150%;">Ingin Jadi Relawan Apa?
</h3>

<div style="
        margin-top: 1em;
        margin-bottom: 5em;
        padding-right:  10%;
        padding-left:  10%;
        text-align: center;
        color: black;
        font-family:Righteous;">
    <a href="{% url 'daftarperawat' id=RS.id %}" style="margin-right: 10%;"><button class = "btndetail"
            type="submit">Perawat</button></a>
    <a href="{% url 'VolunteerNonPerawat:index' id=RS.id %}"><button class = "btndetail" type="submit">Non-Perawat</button></a>
</div>

<div style="
        margin-top: -2%;
        margin-bottom: 5em;
        padding-right:  10%;
        padding-left:  10%;
        text-align: center;
        color: black;
        font-family:Righteous;">
    <!-- buat daftar pekerjaan sama list pekerjaan -->
    <a href="{% url 'RumahSakit:list-pendaftar' RS.id %}" style="margin-right: 3%;"><button class = "btndetail"
            type="submit">List Pendaftar</button></a>
</div>
{% endblock %}

RumahSakit/templates/list-RS.html
{% extends 'RumahSakit/base.html' %} {% load static %} {% block content %}
<title>KamiBisa - List Lowongan Relawan</title>
<div>
    <h1 style="color: black; font-family:Righteous;" class="textJudul">Pilih Rumah Sakit yang Ingin Dibantu</h1>
</div>
<div class="table">
    <table style="font-family: Open Sans;width: 100%;">
        <tr style="text-align:center; font-family:Righteous;">
            <th>Nama Rumah Sakit</th>
            <th>Alamat</th>
            <th>Slot Perawat</th>
            <th>Slot Non-Perawat</th>
        </tr>
        {% for RS in all_RS %}
        <tr style="text-align: center;" class=" text-sm-center">
            <td>
                <a class="link-web" href="{% url 'RumahSakit:detailRS' RS.pk %}">
                    <p style="color: blue;">{{ RS.nama }}</p>
                </a>
            </td>
            <td>{{ RS.alamat }} </td>
            <td>{{ RS.jml_prwt }} </td>
            <td>{{ RS.jml_non }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

</div>

</div>
{% endblock %}

RumahSakit/templates/list_pendaftar.html
<html>

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>KamiBisa</title>
    <link rel="stylesheet" href="{% static 'TK1_PPW/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'TK1_PPW/css/basic.css'%}">
    <link rel="stylesheet" href="{% static 'RumahSakit/css/list_pendaftar.css'%}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Righteous&display=swap"
        rel="stylesheet">
</head>

<body>
    <!-- header-->
    <nav style="background-color: #0077B650; font-family:Roboto" class="navbar navbar-expand-lg navbar-light ">
        <a style="font-size: 200%; color: #000000" class="navbar-brand text-lg-center" href="/">
            Kami<span style="color: #EB5757; margin-right:5%;">bisa</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav" style="margin-left: auto;">
                <li class="nav-item active">
                    <a class="nav-link" href="/" style="font-size: 200%;">Home <span
                            class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- endheader-->
    <section class="registered-list">
        <span class="header">{{RS.nama}}</span>
        <span class="address">
            Alamat: <span class="address-data">{{RS.alamat}}</span>
        </span>
        <table class="divider">
            <tbody>
                <tr>
                    <th>List Perawat</th>
                    <th>List Non Perawat</th>
                </tr>
            </tbody>
        </table>
        <table class="content">
            <tbody>
                <tr class="header">
                    <th class="header">Name</th>
                    <th class="header">Alasan</th>
                    <th class="header">Name</th>
                    <th class="header">Alasan</th>
                </tr>
                {% for perawat, nonperawat in listVolunteer %}
                <tr>
                    {% if perawat != None %}
                    <td>{{perawat.nama}}</td>
                    <td>{{perawat.alasan}}</td>
                    {% else %}
                    <td></td>
                    <td></td>
                    {% endif %}
                    {% if nonperawat != None %}
                    <td>{{nonperawat.nama}}</td>
                    <td>{{nonperawat.alasan}}</td>
                    {% else %}
                    <td></td>
                    <td></td>
                    {% endif %}

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
</body>

</html>