Kantor/urls.py
from django.urls import path
from Kantor.views import list_lowongan, detail_pekerjaan, daftar_lowongan, list_applicants

urlpatterns = [
    path('', list_lowongan, name='list-lowongan'),
    path('tambah-lowongan/', daftar_lowongan, name='tambah-lowongan'),
    path('<pk>', detail_pekerjaan, name='detail-lowongan'),
    path('list-of-applicants/P<int:job_id>',
         list_applicants, name='list-of-applicants'),


    #path('<kode>', detail_course, name='detail-course'),
]

TK_PPW_C09/urls.py
from django.contrib import admin
from django.urls import path, include
from TK1_PPW import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('TK1_PPW.urls'), name='LandingPage'),
    path('Jobseeker/', include('Jobseeker.urls'), name='Jobseeker'),
    path('Kantor/', include('Kantor.urls'), name='Kantor'),
    path('VolunteerNonPerawat/', include('VolunteerNonPerawat.urls'), name='VolunteerNonPerawat'),
    path('RumahSakit/', include('RumahSakit.urls'), name='RumahSakit'),
    path('Perawat/', include('Perawat.urls'), name='Perawat'),
]

VolunteerNonPerawat/urls.py
from django.urls import path

from . import views

app_name = 'VolunteerNonPerawat'

urlpatterns = [
    path('<int:id>', views.index, name='index'),
    path('add/<int:id>', views.add_vnp, name='add-vnp'),
    # path('delete/<int:id>/', views.delete_vnp, name='delete-vnp')
]

VolunteerNonPerawat/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from RumahSakit.models import RS

class VolunteerNonPerawat(models.Model):
    PROVINSI = (
        ('1', 'Aceh'),
        ('2', 'Sumatra Utara'),
        ('3', 'Sumatra Barat'),
        ('4', 'Riau'),
        ('5', 'Kepulauan Riau'),
        ('6', 'Bengkulu'),
        ('7', 'Jambi'),
        ('8', 'Sumatra Selatan'),
        ('9', 'Bangka Belitung'),
        ('10', 'Lampung'),
        ('11', 'Banten'),
        ('12', 'Jawa Barat'),
        ('13', 'DKI Jakarta'),
        ('14', 'Jawa Tengah'),
        ('15', 'Yogyakarta'),
        ('16', 'Jawa Timur'),
        ('17', 'Bali'),
        ('18', 'NTB'),
        ('19', 'NTT'),
        ('20', 'Kalimantan Timur'),
        ('21', 'Kalimantan Barat'),
        ('22', 'Kalimantan Selatan'),
        ('23', 'Kalimantan Tengah'),
        ('24', 'Kalimantan Utara'),
        ('25', 'Gorontalo'),
        ('26', 'Sulawesi Barat'),
        ('27', 'Sulawesi Tengah'),
        ('28', 'Sulawesi Selatan'),
        ('29', 'Sulawesi Tenggara'),
        ('30', 'Sulawesi Utara'),
        ('31', 'Maluku'),
        ('32', 'Maluku Utara'),
        ('33', 'Papua Barat'),
        ('34', 'Papua'),
    )

    nama = models.CharField(max_length=100, null=True)
    umur = models.IntegerField(
        validators=[
            MaxValueValidator(55),
            MinValueValidator(17)
        ], null=True)
    email = models.EmailField(null=True)
    provinsi = models.CharField(max_length=2, choices=PROVINSI, null=True)
    no_telp = models.IntegerField(
        validators=[
            MaxValueValidator(999999999999),
            MinValueValidator(99999)
        ], null=True)
    kota = models.CharField(max_length=50, null=True)
    pengalaman = models.TextField(null=True)
    alasan = models.TextField(null=True)
    rumah_sakit = models.ForeignKey(RS, on_delete=models.CASCADE, null = True, blank = True)

VolunteerNonPerawat/forms.py
from django.forms import ModelForm
from .models import VolunteerNonPerawat

class AddForm(ModelForm):
    class Meta:
        model = VolunteerNonPerawat
        fields = [
            'nama',
            'umur',
            'email',
            'provinsi',
            'kota',
            'no_telp',
            'pengalaman',
            'alasan'
        ]

VolunteerNonPerawat/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseRedirect
from .forms import AddForm
from .models import VolunteerNonPerawat
from RumahSakit.models import RS

choices = [
    ('1', 'Aceh'),
    ('2', 'Sumatra Utara'),
    ('3', 'Sumatra Barat'),
    ('4', 'Riau'),
    ('5', 'Kepulauan Riau'),
    ('6', 'Bengkulu'),
    ('7', 'Jambi'),
    ('8', 'Sumatra Selatan'),
    ('9', 'Bangka Belitung'),
    ('10', 'Lampung'),
    ('11', 'Banten'),
    ('12', 'Jawa Barat'),
    ('13', 'DKI Jakarta'),
    ('14', 'Jawa Tengah'),
    ('15', 'Yogyakarta'),
    ('16', 'Jawa Timur'),
    ('17', 'Bali'),
    ('18', 'NTB'),
    ('19', 'NTT'),
    ('20', 'Kalimantan Timur'),
    ('21', 'Kalimantan Barat'),
    ('22', 'Kalimantan Selatan'),
    ('23', 'Kalimantan Tengah'),
    ('24', 'Kalimantan Utara'),
    ('25', 'Gorontalo'),
    ('26', 'Sulawesi Barat'),
    ('27', 'Sulawesi Tengah'),
    ('28', 'Sulawesi Selatan'),
    ('29', 'Sulawesi Tenggara'),
    ('30', 'Sulawesi Utara'),
    ('31', 'Maluku'),
    ('32', 'Maluku Utara'),
    ('33', 'Papua Barat'),
    ('34', 'Papua'),
]
CHOICES_CLEANED = []
for i in choices:
    CHOICES_CLEANED.append(i[1])

def index(request, id):
    form_pelamar = AddForm()
    vnp_list = VolunteerNonPerawat.objects.all()
    return render(request, 'index.html', {'form' : form_pelamar, 'listProvinsi': CHOICES_CLEANED, 'vnp_list' : vnp_list, 'id' : id})

def add_vnp(request, id):
    form = AddForm(request.POST or None)
    rumahsakit = RS.objects.get(id=id)
    if (form.is_valid() and request.method == 'POST'):
        data = form.cleaned_data
        vnp = VolunteerNonPerawat()
        vnp.nama = data['nama']
        vnp.umur = data['umur']
        vnp.email = data['email']
        vnp.provinsi = request.POST['provinsi']
        vnp.kota = data['kota']
        vnp.pengalaman = data['pengalaman']
        vnp.alasan = data['alasan']
        vnp.rumah_sakit = rumahsakit
        vnp.save()
        form.save()
    return HttpResponseRedirect('/')

# def delete_vnp(request, id):
#     activity = get_object_or_404(VolunteerNonPerawat, id=id)
#     activity.delete()
#     return redirect('VolunteerNonPerawat:index')

VolunteerNonPerawat/templates/index.html
<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>KamiBisa</title>
        <link rel="stylesheet" href="{% static 'TK1_PPW/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'TK1_PPW/css/basic.css'%}">
        <link rel="stylesheet" href="{% static 'VolunteerNonPerawat/css/style.css'%}">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@600&family=Roboto&display=swap" rel="stylesheet">
    </head>
    <body>
        <!-- header-->
        <nav style="background-color: #0077B650; font-family:Roboto" class="navbar navbar-expand-lg navbar-light ">
            <a style="font-size: 200%; color: #000000" class="navbar-brand text-lg-center" href="/">
                Kami<span style="color: #EB5757; margin-right:5%;">bisa</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav" style="margin-left: auto;">
                <li class="nav-item active">
                    <a class="nav-link" href="/" style="font-size: 200%;">Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            </div>
        </nav>
        <!-- endheader-->

        <section class="form">
            <form action="{% url 'VolunteerNonPerawat:add-vnp' id=id %}" method="POST">
                {% csrf_token %}
                <label class="header">Daftar Menjadi Relawan Sekarang!</label>
                <div class="content">
                    <div class="left-side">
                        <label class="body">Nama:</label>
                        <input type="text" name="nama" maxlength="100" required>
                        <label class="body">Umur:</label>
                        <input type="number" name="umur" min="17" max="55" required>
                        <label class="body">Email:</label>
                        <input type="email" name="email" maxlength="100" required>
                        <label class="body">Asal Provinsi:</label>
                        <select name="provinsi">
                            {% for provinsi in listProvinsi %}
                            <option value="{{forloop.counter}}">{{provinsi}}</option>
                            {% endfor %}
                        </select>
                        <label class="body">Asal Kota:</label>
                        <input type="text" name="kota" maxlength="50" required>
                        <label class="body">No Telp:</label>
                        <input id="no_telp-box" type="text" name="no_telp" min="99999" max="999999999999" required>
                    </div>
                    <div class="right-side">
                        <span class="body">Ceritakan pengalaman Anda sebelumnya dalam menjadi relawan:</span>
                        <span class="body"></span>
                        <input class="desc-box" type="text" name="pengalaman" required>
                        <span class="body">Alasan ingin menjadi relawan:</span>
                        <input class="desc-box" type="text" name="alasan" required>
                        <button type="submit" class="body" id="submit">Daftar</button>
                    </div>
                </div>
            </form>
            {% comment %} <div style="display: flex; flex-flow: column wrap; margin-left: 3rem;">
                    <label style="margin-top: 1.5rem; font-weight: bold; font-family: 'Kanit', sans-serif; font-size: 1.25rem;">List VolunteerNonPerawat</label>
                    <br>
                    {% if vnp_list %}
                    {% for vnp in vnp_list %}
                    <form action="{% url 'VolunteerNonPerawat:delete-vnp' vnp.id %}" method="POST" style="display: flex; flex-flow: column wrap; margin-left: 0;">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ vnp.id }}">
                        <label>- {{ vnp.nama }} <button type="submit" style="width: 2rem">X</button></label>
                        <label>> Nama: {{ vnp.nama }}</label>
                        <label>> Umur: {{ vnp.umur }}</label>
                        <label>> Email: {{ vnp.email }}</label>
                        <label>> Provinsi: {{ vnp.provinsi }}</label>
                        <label>> Kota: {{ vnp.kota }}</label>
                        <label>> Pengalaman: {{ vnp.pengalaman }}</label>
                        <label>> Alasan: {{ vnp.alasan }}</label>
                    </form> 
                    <br>
                    {% endfor %}
                    {% endif %}
                </div> {% endcomment %}
        </section>
    </body>
</html>