Kantor/urls.py
from django.urls import path
from Kantor.views import list_lowongan, detail_pekerjaan, daftar_lowongan, list_applicants

urlpatterns = [
    path('', list_lowongan, name='list-lowongan'),
    path('tambah-lowongan/', daftar_lowongan, name='tambah-lowongan'),
    path('<pk>', detail_pekerjaan, name='detail-lowongan'),
    path('list-of-applicants/P<int:job_id>',
         list_applicants, name='list-of-applicants'),


    #path('<kode>', detail_course, name='detail-course'),
]

RumahSakit/urls.py
from django.urls import path
from . import views

app_name = 'RumahSakit'

urlpatterns = [
    path('daftarRS/', views.daftarRS, name='daftarRS'),
    path('listRS/', views.listRS, name = 'listRS'),
    path('<int:id>/', views.detailRS, name='detailRS'),
    path('ListPendaftar/<int:id>', views.list_pendaftar, name='list-pendaftar')
]

TK1_PPW/urls.py
from django.urls import path

from . import views

app_name = 'TK1_PPW'

urlpatterns = [
    path('', views.home, name='home')
]

TK_PPW_C09/urls.py
from django.contrib import admin
from django.urls import path, include
from TK1_PPW import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('TK1_PPW.urls'), name='LandingPage'),
    path('Jobseeker/', include('Jobseeker.urls'), name='Jobseeker'),
    path('Kantor/', include('Kantor.urls'), name='Kantor'),
    path('VolunteerNonPerawat/', include('VolunteerNonPerawat.urls'), name='VolunteerNonPerawat'),
    path('RumahSakit/', include('RumahSakit.urls'), name='RumahSakit'),
    path('Perawat/', include('Perawat.urls'), name='Perawat'),
]

TK1_PPW/models.py
from django.db import models

# Create your models here.

TK1_PPW/views.py
from django.shortcuts import render
from RumahSakit.models import RS

# Create your views here.
def home(request):
    return render(request, "base.html")

TK1_PPW/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <!-- for social media icons -->
  {% block static %}{% endblock %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'TK1_PPW/css/bootstrap.css' %}">

  <link rel="stylesheet" href="{% static 'TK1_PPW/css/basic.css' %}">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}KamiBisa{% endblock %}</title>
</head>

<body>

  <!-- header-->


  <nav style="background-color: #0077B650; font-family:Roboto" class="navbar navbar-expand-lg navbar-light ">
    <a style="font-size: 200%;" class="navbar-brand text-lg-center" href="/">Kami <span
        style="color: #E2696A; margin-right:5%;">
        Bisa
      </span>
    </a>

    <div style="" class="navTulis">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="RumahSakit/listRS">List Rumah Sakit <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'list-lowongan' %}">Cari Kerja <span class="sr-only">(current)</span></a>
        </li>

      </ul>
    </div>
  </nav>
  <!-- endheader-->

  <div class="section">
    <div class="a"><img class="respImg" src="{% static 'Jobseeker/img/a.jpg' %}" width="400" height="300"></div>
    <div class="tulisan">
      <h3>Pandemi covid sedang terjadi...</h3>
      <h3>Banyak yang terdampak...</h3>
      <h3>Semua orang Perlu Bantuanmu...</h3>
      <br>
      <h3>Siapkah kamu untuk menyalurkan tangan </h3>
      <h3>untuk yang membutuhkan?</h3>
    </div>
    <a href="RumahSakit/listRS"><button class="btn">DAFTAR MENJADI RELAWAN</button></a>
  </div>

  <hr>

  <div class="section">
    <div class="a"><img class="respImg" src="{% static 'Jobseeker/img/b.jpg' %}" width="400" height="300"></div>
    <div class="tulisan">
      <h3>Anda terdampak dan perlu pekerjaan?</h3>
    </div>
    <a href="{% url 'list-lowongan' %}"><button class="btn">CARI KERJA</button></a>
  </div>

  <hr>

  <div class="section">
    <div class="a"><img class="respImg" src="{% static 'Jobseeker/img/c.jpg' %}" width="400" height="300"></div>
    <div class="tulisan">
      <h3>Pandemi covid sedang terjadi...</h3>

      <h3>Tingkat okupansi rumah sakit semakin meningkat...</h3>
      <h3>Kebutuhan akan tenaga medis pun meningkat...</h3>
      <br>
      <h3>Apakah Rumah Sakit Anda kekurangan tenaga keperawatan
        <h3>atau membutuhkan relawan untuk tes vaksin?</h3>
    </div>
    <a href="{% url 'RumahSakit:daftarRS' %}"><button class="btn">DAFTARKAN RUMAH SAKIT</button></a>
  </div>

  <hr>

  <div class="section">
    <div class="a"><img class="respImg" src="{% static 'Jobseeker/img/d.jpg' %}" width="400" height="300"></div>
    <div class="tulisan">
      <h3>Sejak pandemi Covid-19...</h3>
      <h3>Banyak orang yang kehilangan pekerjaan mereka...</h3>
      <br>
      <h3>Apakah usaha anda membutuhkan</h3>
      <h3>tenaga profesional dan terpercaya?</h3>
      <h3>
        Mari bantu mereka!</h3>
    </div>
    <a style="color: white;" href="{% url 'tambah-lowongan' %}"><button class="btn">BUKA LOWONGAN PEKERJAAN</button></a>
  </div>

</body>

</html>

TK1_PPW/templates/daftar_relawan.html
<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>KamiBisa</title>
        <link rel="stylesheet" href="{% static 'TK1_PPW/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'TK1_PPW/css/basic.css'%}">
        <link rel="stylesheet" href="{% static 'TK1_PPW/css/daftar_relawan.css'%}">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@600&family=Roboto&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Righteous&display=swap" rel="stylesheet">
    </head>
    <body>
        <!-- header-->
        <nav style="background-color: #0077B650; font-family:Roboto" class="navbar navbar-expand-lg navbar-light ">
            <a style="font-size: 200%; color: #000000" class="navbar-brand text-lg-center" href="/">
                Kami<span style="color: #EB5757; margin-right:5%;">bisa</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav" style="margin-left: auto;">
                <li class="nav-item active">
                    <a class="nav-link" href="/" style="font-size: 200%;">Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            </div>
        </nav>
        <!-- endheader-->
        <section class="choose_hospital">
            <span class="header">Pilih Rumah Sakit Yang Ingin Dibantu</span>
            <div class="content">
                <div>
                    <span class="column" id="header">Nama Rumah Sakit</span>
                    <span class="column" id="header">Alamat</span>
                    <span class="column" id="slot">
                        <span class="top">Slot</span>
                        <span>Perawat</span>
                    </span>
                    <span class="column" id="slot">
                        <span class="top2">Slot</span>
                        <span>Non Perawat</span>
                    </span>
                </div>
                {% if rs_list %}
                {% for rs in rs_list %}
                <div>
                    {% comment %} <a href="{{ rs.id }}/" class="column">{{ rs.nama }}</a> {% endcomment %}
                    <a href="RumahSakit/{{ rs.id }}/" class="column">{{ rs.nama }}</a>
                    <span class="column">{{ rs.alamat }}</span>
                    <span class="column">{{ rs.jml_prwt }}</span>
                    <span class="column">{{ rs.jml_non }}</span>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            {% comment %} <div class="content">
                <span class="column">Nama Rumah Sakit</span>
                <span class="column">Alamat</span>
                <div class="slot">
                    <span class="column" id="header">Slot</span>
                    <span class="column">Perawat</span>
                </div>
                <div class="slot">
                    <span class="column" id="header2">Slot</span>
                    <span class="column">Non Perawat</span>
                </div>
            </div> {% endcomment %}
        </section>
    </body>
</html>